#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Aug 07 16:53:18 PDT 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim InputBuffer_tb_behav -key {Behavioral:sim_1:Functional:InputBuffer_tb} -tclbatch InputBuffer_tb.tcl -view /home/cj/vivado_projects/systolic_array/systolic_array_project/MAC_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/SystolicArray_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/in_cntrl_logic_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/InputBuffer_tb_behav.wcfg -log simulate.log"
xsim InputBuffer_tb_behav -key {Behavioral:sim_1:Functional:InputBuffer_tb} -tclbatch InputBuffer_tb.tcl -view /home/cj/vivado_projects/systolic_array/systolic_array_project/MAC_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/SystolicArray_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/in_cntrl_logic_tb_behav.wcfg -view /home/cj/vivado_projects/systolic_array/systolic_array_project/InputBuffer_tb_behav.wcfg -log simulate.log

